Add missing newline on eof
MacOS is choking on these:

/Users/gitlab/builds/libssh/libssh-mirror/src/packet_cb.c:508:2: error: no newline at end of file [-Werror,-Wnewline-eof]
}
 ^
1 error generated.

Signed-off-by: Jakub Jelen <jjelen@redhat.com>
Reviewed-by: Pavol Žáčik <pzacik@redhat.com>
Merge-Request: <https://gitlab.com/libssh/libssh-mirror/-/merge_requests/823>